import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {requirePreview} from './preview_gate.mjs';
const p=fs.mkdtempSync(path.join(os.tmpdir(),'tour-gate-test-'));const write=(n,v)=>fs.writeFileSync(path.join(p,n),JSON.stringify(v));const hash=n=>crypto.createHash('sha256').update(fs.readFileSync(path.join(p,n))).digest('hex');
try{
 write('tour.json',{schemeSha256:'synthetic'});write('scene.json',{renderSettings:{size:[1280,720]},materials:['a']});fs.copyFileSync(path.join(p,'scene.json'),path.join(p,'preview-scene.json'));fs.writeFileSync(path.join(p,'geometry.bin'),'test geometry');fs.writeFileSync(path.join(p,'renderer.html'),'test renderer');
 const r={schema:'homeowner-preview-review/1',status:'passed',reviewedBy:'synthetic test fixture',tourSha256:hash('tour.json'),schemeSha256:'synthetic',geometrySha256:hash('geometry.bin'),rendererSha256:hash('renderer.html'),sceneArtifact:{path:'preview-scene.json',sha256:hash('preview-scene.json')},checks:Object.fromEntries(['turnSamplesViewed','wholePreviewViewed','subjectsReadable','paceComfortable','noBlankCaptureEdges'].map(k=>[k,true])),artifacts:{}};
 for(const k of ['turnSamples','wholePreview','subjectAudit','meshAudit']){write(k+'.json',{tourSha256:hash('tour.json'),schemeSha256:'synthetic',status:'pass',meshAudit:{hits:[]},errors:[]});r.artifacts[k]={path:k+'.json',sha256:hash(k+'.json')};}
 write('review.json',r);const test=()=>requirePreview(path.join(p,'review.json'),path.join(p,'tour.json'),p);
 assert.throws(()=>requirePreview(null,path.join(p,'tour.json'),p));test();write('scene.json',{renderSettings:{size:[1920,1080]},materials:['a']});test();
 write('scene.json',{renderSettings:{size:[1920,1080]},materials:['changed']});assert.throws(test);write('scene.json',{renderSettings:{size:[1920,1080]},materials:['a']});r.tourSha256='stale';write('review.json',r);assert.throws(test);r.tourSha256=hash('tour.json');r.checks.paceComfortable=false;write('review.json',r);assert.throws(test);console.log('Preview gate: missing/stale/failed blocks; resolution-only transfer passes');
}finally{fs.rmSync(p,{recursive:true,force:true});}
